source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Comment out this line if working on cineio-ios
#pod 'cineio-broadcast-ios', '~> 0.7'

# Uncomment this line if working on cineio-ios
pod 'cineio-broadcast-ios', path: '/Users/WilliamShi/Desktop/HoopMediaStreamer/jrstv/jrstv-broadcast-ios'

# Uncomment this line if working on VideoCore
pod 'VideoCore', path: '/Users/WilliamShi/Desktop/HoopMediaStreamer/jrstv/VideoCore'

pod 'SocketRocket', '~> 0.3.1-beta2'
pod 'socket.IO', '~> 0.5.2'
pod 'ASIHTTPRequest', '~> 1.8.2'
